# Model & checkpoint parameters
dataset: stocks
dataset_path: datasets/all_stocks_dataset.jsonl
device: cuda:0
ckpt: lightning_logs/version_21/best_checkpoint.ckpt
diffusion_config: diffusion_small_config
context_length: 360
prediction_length: 30
use_lags: false
use_features: false
init_skip: true
scaling_type: mean