# Model & checkpoint parameters
dataset: aapl
dataset_path: datasets/aapl_dataset.jsonl
device: cuda:0
ckpt: lightning_logs/version_18/best_checkpoint.ckpt
diffusion_config: diffusion_small_config
context_length: 500
prediction_length: 30
use_lags: false
use_features: false
init_skip: true
scaling_type: mean