model: unconditional
diffusion_config: diffusion_small_config
normalization: mean
use_features: False
use_lags: False
dataset: gbm
dataset_path: data/exp18/coif2-gbm-0.jsonl
freq: D
context_length: 238 # 360 for `D`  181 (for 252)
prediction_length: 1 # 30 for `D`  24
lr: 1.e-3
init_skip: False
gradient_clip_val: 0.5
max_epochs: 500
num_batches_per_epoch: 128
batch_size: 64
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 4
use_validation_set: True
eval_every: 50
device: cuda:0
setup: forecasting
do_final_eval: True
